// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	context "context"

	lock "github.com/divpro/cve/internal/entity/lock"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Acquire provides a mock function with given fields: ctx, id, worker
func (_m *Repository) Acquire(ctx context.Context, id int64, worker lock.WorkerFn) (lock.Lock, error) {
	ret := _m.Called(ctx, id, worker)

	var r0 lock.Lock
	if rf, ok := ret.Get(0).(func(context.Context, int64, lock.WorkerFn) lock.Lock); ok {
		r0 = rf(ctx, id, worker)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(lock.Lock)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64, lock.WorkerFn) error); ok {
		r1 = rf(ctx, id, worker)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
