version: '3.5'

services:
#  app:
#    container_name: cve-app
#    depends_on:
#      - postgres
#    build: .
#    ports:
#      - "8080:80"
#    command: ["/cve"]
#    restart: unless-stopped
  postgres:
    container_name: cve-db
    image: postgres
    environment:
      POSTGRES_USER: pg-user
      POSTGRES_PASSWORD: pg-pass
      POSTGRES_DB: pg-db
    ports:
      - "5432:5432"
    restart: unless-stopped
